GET http://localhost:3000/api/plans
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoidXN1YXJpb0B1cGYuYnIiLCJuYW1lIjoidXN1YXJpbyIsImlhdCI6MTc4Nzg3NzI1NCwiZXhwIjoxNzg3OTYzNjU0fQ.pd5lPLJ_g6dZ5FnE2K6efP7Jw9nlQEoXTeX9bbfWylE

###
GET http://localhost:3000/api/plans/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoidXN1YXJpb0B1cGYuYnIiLCJuYW1lIjoidXN1YXJpbyIsImlhdCI6MTc4Nzg3NzI1NCwiZXhwIjoxNzg3OTYzNjU0fQ.pd5lPLJ_g6dZ5FnE2K6efP7Jw9nlQEoXTeX9bbfWylE

###
POST http://localhost:3000/api/plans
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoidXN1YXJpb0B1cGYuYnIiLCJuYW1lIjoidXN1YXJpbyIsImlhdCI6MTc4Nzg3NzI1NCwiZXhwIjoxNzg3OTYzNjU0fQ.pd5lPLJ_g6dZ5FnE2K6efP7Jw9nlQEoXTeX9bbfWylE

{
    "name": "Plano Premium",
    "price": 49.99
}

###
POST http://localhost:3000/api/plans
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoidXN1YXJpb0B1cGYuYnIiLCJuYW1lIjoidXN1YXJpbyIsImlhdCI6MTc4Nzg3NzI1NCwiZXhwIjoxNzg3OTYzNjU0fQ.pd5lPLJ_g6dZ5FnE2K6efP7Jw9nlQEoXTeX9bbfWylE

{
  "name": "Plano Basic",
  "price": 19.99
}

###
PUT http://localhost:3000/api/plans/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoidXN1YXJpb0B1cGYuYnIiLCJuYW1lIjoidXN1YXJpbyIsImlhdCI6MTc4Nzg3NzI1NCwiZXhwIjoxNzg3OTYzNjU0fQ.pd5lPLJ_g6dZ5FnE2K6efP7Jw9nlQEoXTeX9bbfWylE

{
  "name": "Plano Intermediário",
  "price": 26.99
}

###
DELETE http://localhost:3000/api/plans/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoidXN1YXJpb0B1cGYuYnIiLCJuYW1lIjoidXN1YXJpbyIsImlhdCI6MTc4Nzg3NzI1NCwiZXhwIjoxNzg3OTYzNjU0fQ.pd5lPLJ_g6dZ5FnE2K6efP7Jw9nlQEoXTeX9bbfWylE
